### ISSUE TITLE
No support for contextual substitutions?

### ISSUE THREAD

**Issue by typiconman** [alif-type/sfd2ufo#17]
Converting sfd file with contextual substitutions gives the following cryptic message:

`Traceback (most recent call last):
  File "/home/name/.local/bin/sfd2ufo", line 33, in <module>
    sys.exit(load_entry_point('sfdLib', 'console_scripts', 'sfd2ufo')())
  File "/home/name/Documents/sfdLib.py/Lib/sfdLib/__main__.py", line 37, in main
    parser.parse()
  File "/home/name/Documents/sfdLib.py/Lib/sfdLib/parser.py", line 1504, in parse
    self._parseChainPosSub(key, section)
  File "/home/name/Documents/sfdLib.py/Lib/sfdLib/parser.py", line 618, in _parseChainPosSub
    assert False, (lkey, kind, subtable)
AssertionError: ('ChainSub2', 'class', 'Contextual Substitution - Soft Dot Removal-1')
`

The offending SFD file is [here](https://github.com/typiconman/fonts-cu/blob/master/Ponomar/PonomarUnicode.sfd).

**Comment by khaledhosny** [comment]
Only coverage contextual substitutions are supported right now.
